import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/(landing)/header";
import { Footer } from "@/app/(landing)/footer";
import {auth} from "@/auth";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (

      <SessionProvider session={session}>
        <html lang="en">
          <body className={inter.className}>
            <div className="min-h-screen flex flex-col bg-gray-50">
              <Header/>
              <main className="lg:max-w-screen-lg  mx-auto flex-1 flex w-full">
                {children}
              </main>
              <Footer/>
            </div>
         </body>
        </html>
      </SessionProvider>

  );
}
