import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/(landing)/header";
import { Footer } from "@/app/(landing)/footer";
import Provider from "@/components/providers/provider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    <body className={inter.className}>

      <div className="min-h-screen flex flex-col">
        <Header/>
        <main className="flex-1 flex flex-col items-center justify-center">

          <Provider>{children}</Provider>
        </main>
        <Footer/>
      </div>
   </body>
    </html>
  );
}
