import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/[locale]/(landing)/header";
import { Footer } from "@/app/[locale]/(landing)/footer";
import {auth} from "@/auth";
import { SessionProvider } from "next-auth/react";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "@/i18n";
import {Toaster} from "@/components/ui/toaster";
import { DotBackgroundDemo } from "@/components/custom-ui/dot-background";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



type Props = {
    children: React.ReactNode;
    params: {
        locale: "ru" | "uz";
    }
};

const RootLayout: React.FC<Props> = async ({
                                               children, params: {locale}}) => {

    const session = await auth();
    const messages = await getMessages(locale);

    return (

            <html lang={locale}>
                <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    <SessionProvider session={session}>
                        <div className="min-h-screen flex flex-col bg-stone-50">
                            <Header/>
                            <main className="lg:max-w-screen-lg  mx-auto flex-1 w-full box-content">
                                {children}
                                <Toaster />
                            </main>
                            <Footer/>

                        </div>
                        
                    </SessionProvider>
                </NextIntlClientProvider>
                </body>
            </html>




    );
}


export default RootLayout;