import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/[locale]/(landing)/header";
import { Footer } from "@/app/[locale]/(landing)/footer";
import {auth} from "@/auth";
import { SessionProvider } from "next-auth/react";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "@/i18n";
import { headers } from 'next/headers';
import {Toaster} from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



type Props = {
    children: React.ReactNode;
    params: {
        locale: "ru" | "uz";
    }
};

const RootLayout: React.FC<Props> = async ({
                                               children, params: {locale}}) => {

    const session = await auth();
    const messages = await getMessages(locale);
    const pathname = headers().get('x-next-pathname') as string;
    const coursesRegex = /courses\/[0-9a-fA-F-]+/;
    const headerStyle = "lg:max-w-screen-2xl mx-auto w-full dark"
    const headerContains = coursesRegex.test(pathname);

    return (

            <html lang={locale}>
                <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    <SessionProvider session={session}>
                      <div className="min-h-screen flex flex-col bg-stone-50">
                        <header id="header" className="sticky top-0 z-[10000] transition-all">
                          <div className={`mx-auto w-full ${!headerContains ? 'lg:max-w-screen-2xl' : 'dark'}`}>
                            <Header />
                          </div>
                        </header>

                        <main className={`${!headerContains ? 'lg:max-w-screen-2xl' : ''}  mx-auto flex-1 w-full box-content`}>
                          {children}
                          <Toaster />
                        </main>
                      </div>

                    </SessionProvider>
                </NextIntlClientProvider>
                </body>
            </html>




    );
}


export default RootLayout;